#vai ler os dois dockerfile e criar containers e gerencia-los
version: "3"

services:
  #criando o container do front
  client:
    build: client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app

  #criando o container do backend
  app:
    build: services
    ports:
      - "3000:3000"
    links:
      - database
    command: npm run dev
  #criando container do banco
  database:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asa
